name: "打包 iPad APP"
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: "極速組裝零件"
        run: |
          flutter pub get
          # 🌟 改成編譯框架模式，這樣它就絕對不會跟您要 Apple ID 認證
          flutter build ios --no-codesign --simulator
          
      - name: "產生成品檔案"
        uses: actions/upload-artifact@v4
        with:
          name: TopMath_Pro_App
          path: build/ios/iphonesimulator/Runner.app